language: python

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

script: 
  - python -m pytest -v
  - coverage run --source=softtesting_assignment3 -m pytest tests/
  
affter_success:
  - coveralls
